### ISSUE TITLE
support for searching for classifiers

### ISSUE THREAD

**Issue by fs111** [clojars/clojars-web#162]
It would be great, if the search allowed searching for classifiers. Background is, that we want to be able on conjars.org (uses clojars-web) to search for jar files with the classifier "provider".

**Comment by wiseman** [comment]
I looked into this a little, but I don't know much about classifiers.  Currently the indexing for search just uses information from the POM, but to determine which classifiers are being used it seems we would have to inspect the repository filesystem, looking for artifacts (*.war and *.jar? others?) whose names can be parsed into `<artifact id>-<version>-<artifact>.{jar,war}`.  Is that correct?

**Comment by danielcompton** [comment]
The classifier should be in the POM too, I think.

**Comment by tobias** [comment]
The classifier probably won't be in the pom, but only on the artifact itself.

From https://maven.apache.org/pom.html:

> The classifier allows to distinguish artifacts that were built from
> the same POM but differ in their content. It is some optional and
> arbitrary string that - if present - is appended to the artifact
> name just after the version number.

So for `foo-1.0.0-sources.jar`, `sources` would be the
classifier. `sources` and `javadoc` are probably the most common
classifiers, but they could be anything.

**Comment by wiseman** [comment]
Classifiers are not something that is currently visible in the clojars interface (that I've seen). Would it be too weird to provide search results where there's no indication of why search provided the results it did?

**Comment by tobias** [comment]
@wiseman - that's a good question - I agree that it may not make much
sense to show results with no indication of why they were matched.

Of the ~90k jars in the repo, only 1174 have classifiers. If we get
rid of `sources` and `javadoc` classifiers, only 413 have non-standard
classifiers, so my take from that is that they aren't used much by the
clojure community (see below for the full list).

I don't think this is worth the effort to actually implement for
clojars itself, since we don't use classifiers much and would have to
add a way to parse and display classifiers in the UI for it to even
make sense.

@fs111 - is conjars still being used/maintained/developed?

```clojure
{"sources" 553,
 "groovydoc" 11,
 "jni" 1,
 "dependencies" 3,
 "admin" 11,
 "aot" 1,
 "metadata" 3,
 "standalone" 4,
 "slim" 26,
 "rabbitmq" 2,
 "engine" 1,
 "meta" 1,
 "tests" 195,
 "all" 9,
 "javadoc" 234,
 "resources" 24,
 "test" 88,
 "datadoc" 7}
 ```

**Comment by fs111** [comment]
@tobias yes, conjars is still being used. We deploy new jars a few times a week. This issue isn't too much of a deal-breaker for us, so don't overthink it, if it is too difficult.

**Comment by tobias** [comment]
Thanks. I'm closing this then.
