### ISSUE TITLE
sub-groups are claimable

### ISSUE THREAD

**Issue by gfredericks** [clojars/clojars-web#292]
I was able to (accidentally) deploy the following artifact despite not owning the `mvxcvi` group: 

https://clojars.org/mvxcvi.com.gfredericks.forks/puget

**Comment by tobias** [comment]
Hmm, this is a thorny one.

If we require membership in all parent groups, we need to treat TLDs
specially, otherwise someone could break lots of deploys by claiming
the 'org', 'com', 'net', etc groups (luckily, no one has yet claimed
one of those three, but I haven't checked all TLDs - a full list is
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains).

I'll give this some more thought, and welcome any and all ideas.

**Comment by gfredericks** [comment]
This sounds difficult.

**Comment by tobias** [comment]
Another list that could be consumed by code: http://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by tobias** [comment]
This is no longer an issue now that group names have to be verified.
