### ISSUE TITLE
[Feature] sort search results output based on # of downloads

### ISSUE THREAD

**Issue by troydm** [clojars/clojars-web#372]
It would be nice (and natural I think) to have search results sorted by # of downloads descending from most downloaded to least downloaded one

**Comment by troydm** [comment]
@tobias does ready mean it's already deployed?

**Comment by tobias** [comment]
No, the `ready` tag really means "ready for work by someone in the community". Issues are generally closed when deployed to production, or have linked commits if they are  works in progress.

**Comment by kganey** [comment]
I took a run at this, but got stymied by the Lucene interop.  Here are some notes that might help the next person:

* Clojars uses [Apache Lucene](https://lucene.apache.org/core/) (v. 4.2.0?) for search results
* Downloads are counted by reading the server log file (https://github.com/ato/clojars-web/blob/master/src/clojars/stats.clj)
* (Providing sample log file data would make it easier for the next person to test their solution)
* Clojars tweaks Lucene's automatic search rankings by multiplying the Lucene document score by up to 2.5 based on the download count
* To rank results strictly on the basis of downloads requires the CustomScoreQuery to provide an implementation of CustomScoreProvider rather than the existing ValueSourceQuery. (Lines 90:135, https://github.com/ato/clojars-web/blob/master/src/clojars/search.clj) 
* I found [this article](http://opensourceconnections.com/blog/2014/03/12/using-customscorequery-for-custom-solrlucene-scoring/) helpful for understanding the CustomScoreProvider
* It should be relatively simple to assemble, but I keep getting an error that [AtomicReaderContext](http://lucene.apache.org/core/4_2_0/core/org/apache/lucene/index/AtomicReaderContext.html) is not defined/found/provided as required by the [CustomScoreProvider constructor](https://lucene.apache.org/core/4_2_0/queries/org/apache/lucene/queries/CustomScoreProvider.html#CustomScoreProvider(org.apache.lucene.index.AtomicReaderContext)).

**Comment by tobias** [comment]
@kganey - thanks for looking at this. I agree, it would be nice if there was a sample stats file, or a way to generate one. I've created #382 to track that.

**Comment by tobias** [comment]
I just added stat file generation to the dev setup task via a05c30e.

**Comment by wiseman** [comment]
I don't think you should rank results strictly on the basis of downloads.  This was the old behavior, which led to poor quality search results, and was fixed almost two years ago. #210 has more information.

**Comment by wiseman** [comment]
Do you have examples of searches and results that you think could be improved?

**Comment by arrdem** [comment]
Depending on the available storage infrastructure, a better baseline heuristic would be to sort by total downloads including a decay factor or using some sort of windowing to pick up "now hot" jars rather than outdated or abandoned jars whose totals have not yet been surpassed.

I don't think you want to drag a real time series database in just for this however.

**Comment by tobias** [comment]
@wiseman - thanks for the history, I didn't realize this was an issue that had been covered before

@arrdem - agreed, I don't think this is something we want to implement, but if someone wants to implement it as a separate tool, we provide all the pieces that would be needed: https://github.com/clojars/clojars-web/wiki/Data

@troydm - I'll echo @wiseman: are there specific search results you are dissatisfied with, or was this a general suggestion?

**Comment by troydm** [comment]
@tobias just general suggestion

**Comment by tobias** [comment]
Thanks @troydm. I'm closing this then.
