### ISSUE TITLE
Current user throttling implementation allows for DOS

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#417]
We currently throttle bad login attempts by tracking the number of
failures for a username, and sleeping an increasing amount each time
(https://github.com/ato/clojars-web/blob/master/src/clojars/web.clj#L79-L96). This
would allow for a DOS, since with enough login failures from enough
clients, all of the http threads could be made to sleep for quite a
while.

One alternate approach would be to not throttle, but lock accounts
after N failures, and store that in a TTL cache that expires after
some painful but reasonable time.

**Comment by sanel** [comment]
How about logging failed attempts and use [fail2ban](http://www.fail2ban.org/wiki/index.php/Main_Page) and iptables/firewall for that? I've managed to defend myself from a couple of medium sized WP DDOS attacks with this approach, let alone you get for free protection for other services, like ssh, http scanning and etc.

Just throwing in some ideas... Btw. I'll jump in and offer my help if necessary :)

**Comment by spencercrissman** [comment]
I looked at this a bit tonight, but don't have an obvious solution. The approach outlined by tobias would work to prevent the DOS, but would simply enable another type of attack: a malicious user could lock out other users via bad login attempts.

I considered perhaps the lockout could be attached not only to the username, but to the username/ip address of the bad request, which seems like it might be viable, but I'm not familiar enough with the 'friend' library to tell if this is possible. I don't see a means of getting the current request's remote ip within the credential fn.

sanel's approach would probably circumvent the need for that, but I don't know enough about fail2ban to implement, so I'll leave this issue to someone else I think.

It does seem like you'd be better off removing the timeout even without an alternate solution, because currently you're enabling a DOS but not really preventing anything. Because the sleep happens **after** the login attempt fails but **not** after it succeeds, a malicious user could brute force simply by launching each attempt in a separate thread. The thread that gets the password correct would return immediately while the others will time out, but the attacker will know within a few moments whether the attempt was successful or not and can kill the unsuccessful requests. For the current implementation to effectively block anyone, the delay would have to be applied before attempting the auth instead, but doing so would open you up to the same issue I mentioned with the alternate approach re: blocking other users unless IP address were also taken into account.

**Comment by kahunamoore** [comment]
Here is a simple way to rate limit per-ip using nginx:

https://lincolnloop.com/blog/rate-limiting-nginx

**Comment by tobias** [comment]
@sanel @spencercrissman @kahunamoore  - thanks for the input! 

We now use fail2ban on the new server, so we could possibly feed it data from the app. However, I think using Nginx for this would be simpler.

Fixing this would be a two-parter: removing the exiting throttling in this repo, and implementing the throttling in the server config repo. I've created an issue over there to track that half: https://github.com/clojars/clojars-server-config/issues/34

**Comment by tobias** [comment]
Fixed via https://github.com/clojars/clojars-server-config/commit/8159f2a5293924142b7cc943a49642e735c0f1e7
