### ISSUE TITLE
Can't verify artifacts signed with ed25519 keys

### ISSUE THREAD

**Issue by skeuomorf** [clojars/clojars-web#420]
error-id:"2036f6c1-11ef-42f3-8102-ec2793ec0b97"

After deploying https://github.com/skeuomorf/udp-wrapper I keep getting the error with id listed above whenever I visit https://clojars.org/udp-wrapper

**Comment by skeuomorf** [comment]
I am closing this as it works properly now.

**Comment by tobias** [comment]
@skeuomorf - it looks like it had an issue trying to parse the pgp key for your account, so you won't see the error if you aren't logged in. Did you log out or update the key in your profile?

**Comment by skeuomorf** [comment]
@tobias So, it appears the error is still there if I log in. My GPG key was my first guess when I encountered the error, because it's ed25519, i.e. whatevert that's parsing it probably can't parse ed25519 keys.

**Comment by tobias** [comment]
This is happening in the code that attempts to verify the signature to
see if the release is valid for promotion. We use the bouncycastle
java api for that, and it does not yet support ed25519.

The "fix" for now would be to not let an exception in the validation
code bubble all the way up, and wait for an implementation in
bouncycastle. This means any artifacts signed with an ed25519 key
can't be promoted. That's probably not a big deal, since the promoted
repo is still an experiment in progress, and not much used at the
moment.

**Comment by skeuomorf** [comment]
Ah, I see. FWIW, I skimmed Bouncy Castle's issue tracker and AFAIK an ed25519 implementation isn't discussed anywhere.

**Comment by tobias** [comment]
We've removed validation as part of the removal of the releases repo (#415), so this is no longer an issue.
