### ISSUE TITLE
Get db tests stable on CI

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#453]
Tests involving the database fail intermittently on travis:
* https://travis-ci.org/clojars/clojars-web/builds/100167544
* https://travis-ci.org/clojars/clojars-web/builds/99787849

**Comment by tobias** [comment]
@xeqi - I recall discussing this briefly at the conj - do you have any insight in to why these are failing?

**Comment by xeqi** [comment]
I don't remember talking about it from the conj but spent some time on it today. Here's my observations:

1. I can't get this to fail locally.  I've let `RET=0; until [ ${RET} -ne 0 ]; do lein test; RET=$?; sleep 5; done` run for a few hours and it consistently passes.
2. All the failures come from checking the return value of `add-jar`.
3. Adding debugging information makes it look like the tables are setup correctly.
4. Tests like `browse-projects-finds-jars` are consistent. It uses `add-jar` without checking the result. This means that the data is correctly going into the table, as it is queried later for assertions.

I haven't tried adding debugging info to a jdbc or yesql fork to determine further what is causing the problem. That could be an interesting next step to track it down.

Since the test use an in-memory db I don't know of any particular place that screams potentially inconsistent to me. I suspect something weird either around the serialization queue, that `add-jar` needs to return something similar to how `add-user` does (though I don't know why that would be inconsistent), or that the yesql queries should end in `<!` instead of `!`.

**Comment by tobias** [comment]
@xeqi - all I remember from our conversation was "ah, those fail sometimes, we need to figure out why" or somesuch. Thanks for digging in - this gives me a place to start looking.

**Comment by tobias** [comment]
Looks like we're good now. Closing.

**Comment by danielcompton** [comment]
:clap:
