### ISSUE TITLE
Security headers

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#481]
I think we're mostly covered already, but it could be good to review the current best practices for security headers.

https://github.com/ring-clojure/ring-defaults has a good lot to use. We may be able to remove much or all of `clojars.http-utils` and just use theirs.

It also seems like the ring-session cookies aren't being set to secure so it would be good to look at that too.

There might be some inspiration in https://github.com/twitter/secureheaders, particularly around CSP.

**Comment by tobias** [comment]
I haven't looked at the headers, but did want to note that the cookies are secure as of https://github.com/clojars/clojars-server-config/commit/3c91e4da028202333dc687381e794d85705c1b72 (note this will only apply to *new* cookies - existing cookies won't be overwritten and will still be `secure == false`).

**Comment by danielcompton** [comment]
Here’s how we do currently: https://securityheaders.com/?q=https%3A%2F%2Fclojars.org&followRedirects=on

**Comment by tobias** [comment]
Here is the report for the CDN: https://securityheaders.com/?q=https%3A%2F%2Frepo.clojars.org&hide=on&followRedirects=on

**Comment by tobias** [comment]
I updated the security headers in #825, including a move to ring-defaults. We now get an A+ from [securityheaders.com](https://securityheaders.com/?q=https%3A%2F%2Fclojars.org&followRedirects=on).

I'm not worried about the repo, since most of those security headers control iframes & css/js content/features, which don't apply.
