### ISSUE TITLE
Delete the "milestones" library so I can publish it under another group

### ISSUE THREAD

**Issue by turbopape** [clojars/clojars-web#500]
Hi Guys, 

I am @turbopape on github.
a while back, I pushed a library, milestones, with the "automagictools" group name on clojars. https://clojars.org/automagic-tools-milestones. actually, the automagic.tools domain expired and I don't have access to its e-mails any more.I am sitll the mainainer of this library on github: https://github.com/turbopape/milestones.
Now I want to move this library into my "turbopape" handle on clojars. 
Can you please help me delete this library so I can publish it back again in clojars under "turbopape" group?
Thank you,
Turbopape

**Comment by danielcompton** [comment]
Hi @turbopape. We delete JARs and groups if they are accidentally published internal libs, have security issues, or there are otherwise consequences to leaving the JARs up. In your case, you're free to start publishing to the new group, but I don't think we want to delete the old one as it can break other people's builds.

**Comment by turbopape** [comment]
Ok. I get it. Thank you very much:)
Le 13 févr. 2016 10:49, "Daniel Compton" <notifications@github.com> a
écrit :
