### ISSUE TITLE
Versions on clojars and in the feed file are sorted in the different order

### ISSUE THREAD

**Issue by smaant** [clojars/clojars-web#563]
For instance in the feed file:

``` clojure
{:group-id "org.clojars.smallrivers", 
 :artifact-id "aleph", 
 ;; ... cut ...
 :versions ["0.2.1-SNAPSHOT" "0.2.1-rc5" "0.2.1-rc4" "0.2.1-alpha2-SNAPSHOT"]}
```

On clojars (https://clojars.org/org.clojars.smallrivers/aleph):
0.2.1-rc5
0.2.1-rc4
0.2.1-SNAPSHOT
0.2.1-alpha2-SNAPSHOT

**Comment by smaant** [comment]
Well, I've done some research and it's less clear now. According to the [maven specification](https://maven.apache.org/ref/3.3.3/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html) 
>* strings are checked for well-known qualifiers and the qualifier ordering is used for 
>  version ordering. Well-known qualifiers (case insensitive) are:
>   * alpha or a
>   * beta or b
>   * milestone or m
>   * rc or cr
>   * snapshot
>   * (the empty string) or ga or final
>   * sp

implementation of versions comparison [in clojars](https://github.com/clojars/clojars-web/blob/master/src/clojars/maven.clj#L158) is correct and version in the feed are sorted correctly. At the same time on clojars web versions are sorted by time (apparently).

So the problem is - common understanding and usage of `SNAPSHOT` (as something under development) is opposite to the maven specification. So basically there're two solutions:
 1. Alter the spec and move `snapshot` to the very top of the list
 2. Abandon sorting by spec and sort them by date

**Comment by tobias** [comment]
I believe the maven ordering is based on a workflow where you drop back to SNAPSHOT between pre-releases, so the flow would be:

* release `0.1.0-SNAPSHOT`
* some time later, release `0.1.0-rc1`, and set the version back to `0.1.0-SNAPSHOT`
* some time later, release `0.1.0-SNAPSHOT` again

since all of those are the development state of `0.1.0` at different points in time. This somewhat non-intuitive sorting is less of an issue in maven land, since SNAPSHOTs and releases (rc1 is considered a release) are generally segregated into different repos, so are rarely sorted together).

Given that the current `:versions` vector is sorted, I'd prefer not to change that sort order. What if instead we included a timestamp in the output for each version that the consumer could then use to sort by date? This could be in conjunction with #564. If we did that, I don't think `:tags` would make sense as the top-level key. Maybe `:versions-meta`?

```
{:group-id "group",
 :artifact-id "artifact",
 :description "Some description",
 :scm
 {:connection "scm:git:git://github.com/group/artifact.git",
  :developer-connection "scm:git:ssh://git@github.com/group/artifact.git",
  :tag "29b16d393ae4c27eada2f5c5ca2df8e7ab8da2cb",
  :url "https://github.com/group/artifact",
  ;; --- new key ---
  :versions-meta [{:version "0.1.2-SNAPSHOT"
                   :date #inst "2016-09-20T17:24:42.766-00:00"
                   :tag "29b16d393ae4c27eada2f5c5ca2df8e7ab8da2cb"},
                  {:version "0.1.1"
                   #inst "2016-09-10T17:24:42.766-00:00"
                   :tag null},
                  {:version "0.1.0"
                   #inst "2016-09-01T17:24:42.766-00:00"
                   :tag "46cc0a88de67f984e8a3bdebd61fc17a2363f4c1"}]},
 ;; ---------------
 :homepage "http://github.com/group/artifact",
 :url "http://github.com/group/artifact",
 :versions ["0.1.2-SNAPSHOT" "0.1.1" "0.1.0"]}
```

**Comment by tobias** [comment]
`:release-date` is now included in `:versions-meta` to allow sorting versions by release time:

```clojure
{:description "Swank server connecting Clojure to Emacs SLIME"
 :scm {:connection "scm:git:git://github.com/technomancy/swank-clojure.git"
       :developer-connection "scm:git:ssh://git@github.com/technomancy/swank-clojure.git"
       :tag "1e4a12001bb52c4341b9bfbe1d9439cf698bc1e1"
       :url "https://github.com/technomancy/swank-clojure"}
 :homepage "http://github.com/technomancy/swank-clojure"
 :group-id "org.tcrawley"
 :artifact-id "swank-clojure"
 :url "http://github.com/technomancy/swank-clojure"
 :versions ["1.5.0-sd" "1.5.0-sd-SNAPSHOT"]
 :versions-meta [{:version "1.5.0-sd"
                  :release-date #inst "2012-03-08T21:38:31.525000000-00:00"
                  :scm-tag "1e4a12001bb52c4341b9bfbe1d9439cf698bc1e1"}
                 {:version "1.5.0-sd-SNAPSHOT"
                  :release-date #inst "2012-03-02T02:38:34.060000000-00:00"
                  :scm-tag "c9a36c5910c00416e26c698b542b617ac5066ffb"}]}
```
