### ISSUE TITLE
Delete request

### ISSUE THREAD

**Issue by ilevd** [clojars/clojars-web#570]
Can you delete versions 
0.1.2
0.1.1
0.1.0
here https://clojars.org/com.anychart/playground-samples-parser ?

I was wrong with license, it need to be MIT License instead of Eclipse Public License.

Thanks.

**Comment by danielcompton** [comment]
To prove ownership of this project, can you push a new version with "Delete me" in the description? You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

**Comment by ilevd** [comment]
Here it is https://clojars.org/com.anychart/playground-samples-parser/versions/0.1.1-SNAPSHOT

**Comment by tobias** [comment]
Unless there is a legal reason to remove these (i.e. releasing under the EPL violates the license of other code), I want to leave these versions. You can always relicense in a new release, and since you are broadening the license (MIT is less restrictive than EPL), users that want MIT can just use the new release.

Note that your repo still [contains the EPL LICENSE file](https://github.com/AnyChart/playground-samples-parser/blob/master/LICENSE), even though your README mentions MIT.
