### ISSUE TITLE
Please delete org.clojars.pedro/monetdb-java-lite

### ISSUE THREAD

**Issue by PedroTadim** [clojars/clojars-web#648]
I will move this jar to the monetdb.org organization

Thanks!

**Comment by danielcompton** [comment]
Hi Pedro

JARs are removed from Clojars for two reasons:

* There is a security vulnerability in a published JAR, i.e. malicious code
* Private credentials or code have been published.

Otherwise JARs are not deleted, to preserve the immutable nature of the Clojars repository. There is no problem with leaving a group around, especially an `org.clojars.*` group, that is intended for you to push forks/experiments/e.t.c.

You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

Thanks!

**Comment by tobias** [comment]
This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
