### ISSUE TITLE
Add Verified tag for official repos

### ISSUE THREAD

**Issue by jgh-** [clojars/clojars-web#674]
Problem:
I am relatively new to the Clojure and Java ecosystem and recently ran into an issue with the `Postgres` repo on Clojars.  The repo is simply called `postgres` and from the name alone appears official.  It is, as it turns out, not official nor is it up to date, however there are old tutorials floating around on the internet that reference it.  The version of the postgres driver on Clojars works for queries but inserts and executes do not work.   It took me several hours to realize that I wasn't doing anything wrong in code, but instead the postgres driver on Clojars is not up-to-date and that I had to get a different one off of Maven instead.

What I would like to propose is that Clojars add a verified tag or some other mechanism for indicating that repos are official.  I don't suggest that you guys go through every repo in existence but that maintainers should reach out and be verified manually via domain or Github or some other means.  Informing users that they can trust a repo will be up to date and compatible would save newbies like me some time and headache, and probably be a valuable mechanism for increasing the trust and usefulness of Clojars :)

**Comment by technomancy** [comment]
I think instead of allowing certain jars to be marked "verified" it would be better to allow certain jars to be marked as "unofficial" or "deprecated". The `postgres` jar is a pretty clear violation of the Clojars recommendations, but unfortunately not in violation of any documented requirements. There's a reasonable argument to be made in favor of deleting it, but we would need to update and clarify the Clojars policy for name-squatting packages in this case.

What I think is less controversial is adding support for deprecation warnings as metadata displayed on a jar's page. These could be created by admins (like in the case of this particular jar) or by project maintainers.

Marking just the bad packages seems a lot more scalable than marking all the good ones, especially as "verified" implies someone going out and doing the work of verification, which we don't have anywhere near the required amount of maintainer time to do.

**Comment by technomancy** [comment]
Actually I just noticed that the author is still active on GitHub for other projects. Hi @jkjuopperi !

Do you think you could deploy a new version of your `postgresql` jar to Clojars which has a description indicating that this is an unofficial version, and pointing potential users towards the up-to-date versions on Central?

**Comment by jkjuopperi** [comment]
It actually is the the official driver jar, but deprecated it is. There is no point in mirroring the PostgreSQL driver in clojars so maybe it should be removed? How can that be done?

**Comment by technomancy** [comment]
> There is no point in mirroring the PostgreSQL driver in clojars so maybe it should be removed? How can that be done?

The FAQ says that the official policy is to only delete jars in the case of security issues: https://github.com/clojars/clojars-web/wiki/About

It may be that deleting the jar is the right thing to do, but I don't want to act hastily at this time. I believe a good interim fix to the problem would be just to deploy a new version which recommends not using this version in the :description section, and if the :url could be changed to something less official-looking that would be good too.

You don't need the original project files around; you can just do `lein new postgresql`, edit project.clj, and `lein deploy clojars` for this.

Thanks!

**Comment by tobias** [comment]
An issue with deleting the jars is the versions that exist on Clojars don't exist on Maven Central, so deleting them would break any projects that are using any of those versions. 

Since this shadows a group/artifact that is on Maven Central, you won't be able to deploy a new version unless I add it to a whitelist (we no longer allow deploys that [shadow artifacts on Maven Central](https://github.com/clojars/clojars-web/wiki/About#why-cant-i-deploy-something-that-uses-a-group--artifact-name-that-exists-on-maven-central) for security reasons. 

Until we come up with a broader/better solution, it probably does make sense to deploy a version with a new description. I'll add this project to the whitelist so that can happen.

**Comment by jkjuopperi** [comment]
Doing scp of pom and jar to clojars@clojars.org didn't seem to work anymore. Should it?

There actually aren't any project files other that pom and jdbc driver jar. If I'm to deploy a working version with altered name/description I have to figure out how to upload them.

I was trying to upload the latest JDBC driver, but would it actually be possible re-upload the current jar with altered pom.xml as only thing we're trying to change is the description on the web?

If you can edit the pom, it could contain something like:

> <name>Deprecated mirror of PostgreSQL JDBC Driver</name>
> <description>This unofficial mirror of PostgreSQL JDBC driver is not kept up to date. Please use [org.postgresql/postgresql "42.1.4"] instead.</description>

**Comment by tobias** [comment]
Clojars no longer supports scp deploys, only deploys via http. But we no longer read the description from the pom on each request, we put it in the db on deploy, so altered it there for all versions to read:

> Deprecated mirror of PostgreSQL JDBC Driver. This unofficial mirror of PostgreSQL JDBC driver is not kept up to date. Please use [org.postgresql/postgresql "42.1.4"] instead.

See https://clojars.org/postgresql/.

Hopefully that will help with the confusion around this particular jar until we can come up with a more general solution.

**Comment by jgh-** [comment]
> What I think is less controversial is adding support for deprecation warnings as metadata displayed on a jar's page. These could be created by admins (like in the case of this particular jar) or by project maintainers.
@technomancy That's another option.  This ticket is mostly to facilitate a discussion that's been going on on the clojurians slack for a few days now in a more official manner (and involving Clojars :))

**Comment by tobias** [comment]
Based off of this discussion, I think it makes sense to do two things:

1. Add a message when displaying an artifact that shadows Maven Central that states such, along with a link to search.maven.org for that group & artifact
2. Add a way to set custom messages to display for particular artifacts. This could be used for deprecation, and would override a shadow message if any. This makes sense for the postgresql jar, since it shadows, but what is shadows isn't what should be used. Initially, this message would come from a file that is part of the build (much like we do the shadow whitelist), and would only be editable by admins (or via PRs). 

How does that sound?

**Comment by jgh-** [comment]
I think that sounds like a good proposal.  Would these messages would appear on the Clojars site or in Lein/Boot? (Or both?)

**Comment by tobias** [comment]
These messages would only appear on the Clojars site, we don't have a mechanism to display messages in lein/boot when you are resolving dependencies. We could possibly include the messages in the results returned from the search API, but I don't know how often those are used from lein/boot.

**Comment by tobias** [comment]
I've deployed the ability to set a custom message, and set one for `postgresql`. See https://clojars.org/postgresql/

I've also added shadowing messages for artifacts that shadow (which is overridden by custom messages). See https://clojars.org/org.tcrawley/dynapath for an example of the stock shadow message.

I'm closing this, but feel free to reopen if you think it needs more discussion.

**Comment by jgh-** [comment]
Looks great! Thanks.
