### ISSUE TITLE
delete-request: com.brunobonaci/clj-sophia

### ISSUE THREAD

**Issue by BrunoBonacci** [clojars/clojars-web#685]
Please delete 

https://clojars.org/com.brunobonaci/clj-shopia
and
https://clojars.org/com.brunobonacci/clj-shopia

A new version with "Delete me" has been pushed.

As a suggestion, you should allow to delete artifacts from the website if they have "0 Downloads",
this could ease the administration burden for artifacts which have been just pushed and nobody ever used.

**Comment by tobias** [comment]
Since the repository can be rsync'ed and we don't get the download stats in realtime (they are calculated nightly from the nginx and CDN logs), we don't have a reliable way to know when a release hasn't been accessed. 

This release doesn't meet the [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar), so I'm closing this issue.
