### ISSUE TITLE
Problem with password resetting

### ISSUE THREAD

**Issue by DeLaGuardo** [clojars/clojars-web#706]
error-id:"7f85ce1b-8e62-47e1-a8ef-0ee743035310"

**Comment by tobias** [comment]
The account you are trying to reset has an invalid email address (it is the same as the username without a domain), so Clojars cannot send out the password reset request. 

In order to fix that, we will need to verify your account another way. There is a GPG public key on the account - if you still have access to the corresponding private key, can you encrypt a file with your email address in it with that key and email it to contact@clojars.org?

**Comment by DeLaGuardo** [comment]
Thanks for finding some time check this out. Unfortunately I don't have access to the private key. But I'm almost sure there is nothing important in that account. So I'm gonna to create new one with different username.
