### ISSUE TITLE
Remove accidental upload

### ISSUE THREAD

**Issue by mgrbyte** [clojars/clojars-web#712]
I accidentally pushed a version of my library with the wrong groupId "ids".
https://clojars.org/ids
Can this be removed please?

**Comment by danielcompton** [comment]
JARs are removed from Clojars for two reasons:

* There is a security vulnerability in a published JAR, i.e. malicious code
* Private credentials or code have been published.

Otherwise JARs are not deleted, to preserve the immutable nature of the Clojars repository.

If your deletion request fits one of the two reasons, push a new version with "Delete me" in the description to prove ownership of it. 

You can find more details on the deletion process [here](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar).

Thanks!
