### ISSUE TITLE
Search for clj-concord doesn't find clj-concordion

### ISSUE THREAD

**Issue by holyjak** [clojars/clojars-web#719]
I believe that both https://clojars.org/search?q=clj-concord&format=json and https://clojars.org/search?q=clj-concordion&format=json should include clj-concordion yet they do not, though the former includes lot of projects that have "clj-" but no "concord" in their name.

I see that _clj-concord_ has 2758 "hits" so perhaps clj-concordion is just not on the first page of 24. But the ranking/matching algorithm seems really weird ...

**Comment by tobias** [comment]
I don't know much about lucene, but if someone who does know know more about it and wants to look at solving this, the search code lives in https://github.com/clojars/clojars-web/blob/master/src/clojars/search.clj. Also see #721.

**Comment by holyjak** [comment]
thanks! I want to fix search for cljdocs so I can look at this one just as
well, when I only find the time...

**Comment by holyjak** [comment]
Hi @tobias ! If you get to work on search, let me know, we can perhaps leverage the code both for clojars and cljdoc. I have re-written search for cljdoc but have to yet incorporate download counts to provide better results. It is better then what it used to be but still not optimal, as can be seen in this thread https://github.com/cljdoc/cljdoc/issues/308

Here is cljdoc in-progress PR to incorporate download counts https://github.com/cljdoc/cljdoc/pull/359 but I am stuck between it having too little effect and having undesirably strong effect. Tuning Lucene is not trivial for me :) I will look more at how clojars does it. Thanks!

**Comment by tobias** [comment]
Hi @holyjak! I finally got around to working on search, and used your cljdoc implementation as the basis for that. It was really helpful, thanks! (see https://github.com/clojars/clojars-web/issues/806#issuecomment-1019521693 for a few more details).

For download counts, the method Clojars was using is no longer supported by Lucene. So I switched to including the calculated boost value in the index, then boosting the query by that value.

The boost is calculated here: https://github.com/clojars/clojars-web/blob/d98939cb91b690eef66d3d3165d3e187ef641d8a/src/clojars/search.clj#L206-L213
added to the index here: https://github.com/clojars/clojars-web/blob/d98939cb91b690eef66d3d3165d3e187ef641d8a/src/clojars/search.clj#L195-L197
and used in the query here: https://github.com/clojars/clojars-web/blob/d98939cb91b690eef66d3d3165d3e187ef641d8a/src/clojars/search.clj#L300

Hopefully that helps with boosting cljdocs results with dowload counts.

As far as the root issue reported here: even with my changes, searching for `clj-concord` won't find `clj-concordion`, since I didn't change the searching to be fuzzy, so you would have to use `clj-concord*` or `concord*`. However, results for those searches should be better now.

**Comment by holyjak** [comment]
Thank you very much, that is wonderful!

**Comment by tobias** [comment]
I don't think we have a good way to fix the root issue here (searching for `clj-concord` does not find `clj-concordian`) without making all searches fuzzy, and doing that would make search less useful overall unfortunately. So I'm going to close this issue.
