### ISSUE TITLE
SSO login via Google or GitHub

### ISSUE THREAD

**Issue by danielcompton** [clojars/clojars-web#728]
We should consider offering an option for SSO login to parties like GitHub/Google. They have whole teams dedicated to security and securing user accounts. Allowing users to delegate this to a much bigger third party would add significant security benefits. This would probably be quite a large piece of work though.

**Comment by renatoalencar** [comment]
Hi, I trying to build it, but wanted to let some discussion here in order to some stuff to be addressed. So I'm going to describe the requirements I imagine it should have and then you guys (@danielcompton and @tobias) could review it.

## Scope

I believe it could be built for only GitHub first as a proof of concept and them expand to other providers later, I believe most Clojars users have GitHub accounts and they could integrate it or register first from GitHub and also some people use different accounts for professional and personal matters.

I would be possible to register from GitHub, to link their accounts to GitHub and then log in back again using GitHub's OAuth.

## Registration

An user goes to the register page, clicks on the GitHub registration button, which redirects to GitHub authorization URL. The user is redirected back to Clojars at the callback URL previously passed with the authorization URL, it then checks if the user is already registered and if not it will create it on the `users` with the `oauth_provider`, `oauth_id` and an `email`.

I think the question here is if the user would be allowed to have more than one provider linked to the account at the same time. Then it would need a different table to keep track of the respective authorization data.

### The user cancels and denies it

GitHub does redirect back to the OAuth app in question? If so, it should redirect to the registration page and show an error message.

### The user is already registered

The less obtrusive path would be just logging the user in.

### The user's email is already registered

Offer an options of logging in and link its GitHub account? Or add the possibility to set another e-mail address?

## Login

An user goes to the Login page and then clicks on the GitHub button, it would be redirected to GitHub authorization URL and redirected back to the passed callback URL. Its session would be created and it would be logged in.

**The edge cases are almost the same as for Registration**. If someone could add some special case here would be interesting.

## Linking

An user already has an account and want to link it to GitHub. On the profile page, there would be a GitHub button that would do the OAuth process and if the user is already logged in, the account would be linked by adding the proper data to the database.

### The account is already linked to another one

It would show an error in the profile page saying the user's GitHub account is already linked to another account.

### Unlink

I think it would be interesting to allow users to unlink their accounts, so they could link to different accounts or maybe remove a compromised one.

## Modeling

It has to be decided if the user will be allowed to have **more than one account in the future**, so the OAuth data would be placed in another table.

**Comment by danielcompton** [comment]
This is a pretty big piece of work, I won't have the time to look at this. @Tobias may or may not, I'm not sure how much of a priority this is for us right now.

**Comment by tobias** [comment]
@danielcompton - @renatoalencar and I had been chatting in a DM on Slack about this. I'm going to try and mentor him on implementing it and plan on doing some review of the design this weekend.

**Comment by renatoalencar** [comment]
I'm currently working on an simple implementation, in order to understand the problem and how to solve it. It will contain the requirements above, and I believe that another use cases will come later. I'm currently using `clj-social`, but I believe that we could end up using another one, since it's main dependency `com.github.scribejava/scribejava-apis` seems to add some complexities to the model.

The current approach I'm following is to build a `friend` workflow and handle everything inside of it. I believe this could be a general abstraction and that would need to just pass the "social" implementation to it.

**Comment by tobias** [comment]
Hi @renatoalencar, I have a few thoughts SSO on Clojars:

**I would prefer to focus just on the login with SSO case initially, and not support registering via SSO**

- We require the user to have a password to make some profile changes (mainly to enable two-factor auth). With that restriction, users would have to still provide a password at registration time. 
- I *think* that just supporting login would mean we don't need to store anything in the database related to SSO. If GitHub gives us an email address when the user logs in via SSO, we can just look up the user and log them in (caveat: I haven't looked GitHub's SSO docs at all, I'm just basing this on how SSO with Google works with the system that I work on for my day job).
- This would be much easier to implement. We could then expand to other providers and/or consider covering registration as well.

**When someone logs in via SSO and has two-factor auth enabled, I think we should ask them for their 2fa code**

This prevents bypassing 2fa when logging in via SSO.

How does that sound?

**Comment by renatoalencar** [comment]
That's seems great, makes simpler and easier to implement. We could just get the GitHub's main user e-mail, the implementation I proposed queries the user's primary e-mail, then it could just validate if it is a verified e-mail. So now we have:

* Users can log in into the website via GitHub's primary e-mail;
* The e-mail must be verified into GitHub;
* If enabled, user's should be asked for 2fa code.

That sounds great, I'll work on something this weekend.

**Comment by tobias** [comment]
We have login via GitHub now thanks to @renatoalencar. I'm closing this issue, we can open a new one if we want to add another provider.
