### ISSUE TITLE
Disable rsync of the on-disk repo

### ISSUE THREAD

**Issue by tobias** [clojars/clojars-web#735]
We hope to eliminate the on-disk repo and just have the cloudfiles-based CDN-fronted repo as the sole repo. This will mean that we will no longer be able to support rsync of the repo.

Based on our rsync logs, it looks like we've had ~100k rsync connections over the last
month from ~100 ip addresses. But the bulk of those requests were over
a few scattered days where a single ip would connect every 2-5
*seconds*. If you are using the rsync feature to maintain a copy of
the repository, please comment here to let us know your use case and we'll see 
if we can come up with an alternate solution.

See https://groups.google.com/d/msg/clojure/ZXBOQD5Ubbc/D4ktv8aFCQAJ for more context.

**Comment by SevereOverfl0w** [comment]
I had intention to rsync a mirror with the intention of performing analysis on the history of Clojure code.

I can also do this using the http API, but it would be more costly in bandwidth for you.

**Comment by tobias** [comment]
@SevereOverfl0w and I [chatted on the Clojurians slack](https://clojurians.slack.com/archives/C0H28NMAS/p1577189637003100) about this. I'm pasting it here since that's not a permanent record: 

> dominicm:  Does cloudfiles have an export functionality of some kind?
> tcrawley:  @dominicm no, just http. I'm not concerned about the cost of crawling the repo via http. We do publish a list of all jars in the repo, updated daily. So that could be used to pull down a copy of the repo, then later check for jars that aren't in the local copy and pull just those. Though that process would also have to have smarts around knowing that maven-metadata.xml files would need to be re-downloaded as well.
> dominicm:  Yeah. If cost isn't a problem, then no worries. My use of rsync was to minimize bandwidth consumption.

**Comment by tobias** [comment]
Rsync is now disabled. Please let us know if this impacts you negatively.

**Comment by z4yx** [comment]
The TUNA open-source software mirror site maintains a copy of Clojars repo for users in China mainland, who have difficulties accessing most CDNs oversea.
As mentioned in the issue above, our service has been affected. Could you provide other methods to help us sync the repo? Thanks.

**Comment by z4yx** [comment]
To my knowledge, USTC also maintains a mirror of Clojars, which is affected too.
https://mirrors.ustc.edu.cn/status/

**Comment by tobias** [comment]
Thanks for the report @z4yx - is it possible for TUNA or USTC to implement the mirror as a caching proxy, requesting missing files from repo.clojars.org?

**Comment by z4yx** [comment]
Since our download speed is quite slow, the reverse proxy can cause user experience issues. 
I noticed that you are hosting files on AWS S3, then I realized we can use the AWS tool to sync files. The command is like `aws --no-sign-request --endpoint-url=https://s3.us-east-2.amazonaws.com/ s3 sync s3://clojars-repo-production/ /local-path`. This method works as long as file indexing enabled.

**Comment by tobias** [comment]
Ah, yes, if you can sync the repo from s3, that would be fine @z4yx. Have you tried it to see if it works? How often will you be synchronizing the repo?

**Comment by z4yx** [comment]
As you can see on https://mirrors.tuna.tsinghua.edu.cn/status/#server-status, recent synchronizations succeed, so this method works fine. The synchronizing interval is 24 hours, the same as most other repositories.

**Comment by tobias** [comment]
Great! Glad to hear that is working @z4yx

**Comment by pmonks** [comment]
Chiming in _very_ late (as I haven't used this code since 2019 and only just learned of this issue), but I have [a little project](https://github.com/pmonks/clojars-dependencies) that attempts to determine downstream dependencies for a given artifact.  It does (or rather, used to) accomplish this by rsyncing all of the POM files hosted on Clojars, parsing those files, and walking the dependency graph "backwards" from a given GAV.  `rsync` was useful for this purpose as it provided both the ability to restrict to just the files I needed (i.e. `*.pom`) as well as efficiently streaming deltas on subsequent runs (once synced, the files remain on disk, with periodic updates as needed).

Am I right in thinking that my only recourse now is to use the [list of POMs API](https://github.com/clojars/clojars-web/wiki/Data#list-of-pom-files) then pull down every single POM file individually every time?  This isn't great, as it's both slower than rsync, and loses the ability to sync just a delta on subsequent runs (unless clojars provides ETag headers, and I start caching them alongside the POMs, I guess).

**Comment by danielcompton** [comment]
@pmonks could you sync the repo from S3 instead? https://github.com/clojars/clojars-web/issues/735#issuecomment-587237185

As a note for any future readers who find this thread, there is a mailing list at https://groups.google.com/g/clojars-mirrors to get notified about these kinds of changes - https://github.com/clojars/clojars-web/wiki/Mirrors#running-an-internal-proxy-or-mirror-of-clojars.

**Comment by pmonks** [comment]
@danielcompton thanks for the reply!

I don't have the `aws` command on all the machines where this code runs, so that's less useful to me than just syncing over HTTP (and making sure to use ETag/If-None-Match).  Am I correct in thinking that HTTP will be a little less "stress" on Clojars' infrastructure anyway, for the use case of copying down every single POM?

**Comment by danielcompton** [comment]
S3 or HTTP are both fine for load, just whatever is most convenient for you.
