### ISSUE TITLE
Get complete info of a package with REST api

### ISSUE THREAD

**Issue by ghost** [clojars/clojars-web#756]
The web api for querying info of a package doesn't return fields like dependencies, license, scm url etc. How do I fetch this info about a pacakge?

**Comment by fctorial** [comment]
Also, how do the field `latest_release` and `latest_version` differ?

**Comment by tobias** [comment]
Those fields are missing from the API only because they have never been added I suspect. A PR adding them would be welcome. Alternatively, you can pull down the pom file for an artifact and parse that to get that information.

`latest_release` will be the version number of the most recent release, including SNAPSHOT releases (so could be something like `0.1.0-SNAPSHOT`).

`latest_version` will be the version number of the most recent non-SNAPSHOT release (so would be something like `0.1.0`).

If the most recent release is not a SNAPSHOT, `latest_release` and `latest_version` will be the same non-SNAPSHOT value.

**Comment by tobias** [comment]
This was implemented in #895 and deployed in 2024-11-13.2126.
