### ISSUE TITLE
Better support for one-off deploy tokens

### ISSUE THREAD

**Issue by vemv** [clojars/clojars-web#811]
## Context

I like to use the deploy tokens as one-off (single-use) ones: that way I get to never store them, which has some associated risks.

## Problem statement

There isn't explicit support for one-off tokens so one has to manually disable them after use. They also accrue quite awkwardly over the web UI:

![image](https://user-images.githubusercontent.com/1162994/133867919-27896f4b-f98c-47d2-b1c4-839061f631d6.png)

## Proposed solution

Offer one-off tokens that can be used once at most (and that maybe are valid only up to 60m from now).

They would not accrue over the web UI.

WDYT?

Thanks - V

**Comment by tobias** [comment]
I think this is a really good idea! The idea of "one use" is a bit tricky, since a single deploy is many requests, but all requests *should* be in the same HTTP session, so we could attach a session identifier to the token on the first request, then only allow future requests within that same session.

I think implementing this would be straightforward. Are you interested in implementing this? If so, I'm happy to help. I can also do this myself, but wanted to give you the opportunity if you were interested.

**Comment by vemv** [comment]
Thanks for the response!

Maybe in a different season I'd be happy to give a PR shot - these days I have quite a lot on my plate (OSS and otherwise)

**Comment by tobias** [comment]
I've added support for single-use tokens, and you can now set an expiry on tokens:

![image](https://user-images.githubusercontent.com/2631/156561790-5e890acb-2c51-4b01-9ca1-3a9cebc05235.png)

You can now also filter the list of tokens on the token management page:

![image](https://user-images.githubusercontent.com/2631/156561885-efb00f8d-8d8c-480d-bb8b-f11b0e03df02.png)

**Comment by vemv** [comment]
Amazing, thank you for the effort!

Will sure start using these exclusively.
